subject_form:
  duration:
    min: 1
course:
  show:
    paginate:
      member: 5
      subject: 5
  name:
    max_length: 255
  description:
    max_length: 255
subject:
  show:
    paginate:
      task: 5
